<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Customer\Block\Account\AuthorizationLink $block
 * @var \Magento\Framework\Escaper $escaper
 */
$dataPostParam = '';
$isRegCus = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
    $isRegCus = "user-loggedin";
}
?>
<div class="link authorization-link <?= $isRegCus; ?>" data-label="<?= $escaper->escapeHtml(__('or')) ?>">
    <a <?= /* @noEscape */ $block->getLinkAttributes() ?>
        <?= /* @noEscape */ $dataPostParam ?>><?= $escaper->escapeHtml($block->getLabel()) ?></a>
</div>
